name: Deploy lib to GitHub branch
on:
  push:
    branches: [main]

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
